# Generated by Django 6.0.5 on 2026-05-15 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('start_time', models.TimeField(verbose_name='начало')),
                ('end_time', models.TimeField(verbose_name='конец')),
                ('reason', models.TextField(blank=True, verbose_name='причина')),
            ],
            options={
                'verbose_name': 'исключение в расписании',
                'verbose_name_plural': 'исключения в расписании',
            },
        ),
        migrations.CreateModel(
            name='StudioSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(verbose_name='день недели (1=Пн, 7=Вс)')),
                ('start_time', models.TimeField(verbose_name='время начала работы')),
                ('end_time', models.TimeField(verbose_name='время окончания работы')),
            ],
            options={
                'verbose_name': 'рабочие часы',
                'verbose_name_plural': 'рабочие часы',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='начало')),
                ('end_time', models.DateTimeField(verbose_name='конец')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('status', models.CharField(choices=[('booked', 'Забронировано'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='booked', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'бронирование',
                'verbose_name_plural': 'бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
