# Generated by Django 6.0.5 on 2026-05-17 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='booking_files/', verbose_name='файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='bookings.booking', verbose_name='бронирование')),
            ],
            options={
                'verbose_name': 'файл бронирования',
                'verbose_name_plural': 'файлы бронирований',
            },
        ),
    ]
