# Generated by Django 6.0.5 on 2026-05-17 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_groupmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmember',
            options={'verbose_name': 'участник группы', 'verbose_name_plural': 'участники группы'},
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='bookings.booking', verbose_name='бронирование'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='телефон'),
        ),
    ]
