# Generated by Django 6.0.5 on 2026-05-18 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_groupmember_options_alter_groupmember_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingfile',
            name='file',
            field=models.FileField(upload_to='booking_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'ppt', 'pptx', 'mp4', 'mov', 'avi'])], verbose_name='файл'),
        ),
    ]
