# Generated by Django 6.0.5 on 2026-05-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_bookingfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingfile',
            name='file',
            field=models.FileField(upload_to='booking_files/', verbose_name='файл'),
        ),
    ]
