# Generated by Django 6.0.5 on 2026-05-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_bookingfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioschedule',
            name='specific_date',
            field=models.DateField(blank=True, null=True, verbose_name='конкретная дата'),
        ),
    ]
